#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Feb  4 15:57:02 2019

@author: akanksha_rajput
"""
import pandas as pd

df = pd.read_csv("input.txt",  encoding = "utf-16be", escapechar="\\", engine = 'python')
print(df)

